name: Build and Upload

on:
  push:
    branches:
    - trunk
  repository_dispatch:
    types:
    - rebuild

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: fkirc/skip-duplicate-actions@v3.4.0
      with:
        cancel_others: true
        concurrent_skipping: same_content
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - uses: actions/checkout@v1
    - run: cat static/s.js static/a.js > static/sa.js && mv static/sa.js static/a.js
    - run: wget https://dl.unrelenting.technology/zola/zola-linux && chmod +x zola-linux
    - run: WMIO_TOKEN=${{ secrets.WMIO_TOKEN }} ./zola-linux build
    - run: AWS_CF_DIST_ID=${{ secrets.AWS_CF_DIST_ID }} TLG_TOKEN=${{ secrets.TLG_TOKEN }} ./sync
